# Generated by Django 4.1.5 on 2023-01-12 14:16

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_id', models.CharField(max_length=100, unique=True, verbose_name='Employ ID Code')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='', unique=True, verbose_name='Phone number')),
                ('gender', models.CharField(choices=[('', 'SELECT GENDER'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=10, verbose_name='Gender')),
                ('doc_image', models.ImageField(upload_to='doctors/')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('', 'SELECT TO UPDATE STATUS'), ('Responded', 'RESPONDED'), ('Waiting', 'WAITING')], default='', max_length=10, verbose_name='Request status')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('', 'SELECT GENDER'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=10, verbose_name='Gender')),
                ('birthdate', models.DateField(max_length=100, verbose_name='Birthdate')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='', unique=True, verbose_name='Phone number')),
                ('address', models.CharField(max_length=150, verbose_name='Location address')),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=100, unique=True, verbose_name='Speciality name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=100, unique=True, verbose_name='Suggestion')),
                ('suggestionDescription', models.TextField(verbose_name='Suggestion description')),
                ('sugg_dated', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.doctor', verbose_name='Doctor to submit suggestion')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.illness', verbose_name="Patient's illness")),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Treatment description')),
                ('date_confirmed', models.DateField(auto_now_add=True)),
                ('illness', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.illness', verbose_name='Illness')),
            ],
        ),
        migrations.CreateModel(
            name='requestTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateTimeField()),
                ('end_period', models.DateTimeField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.illness', verbose_name='Treatment request')),
            ],
        ),
    ]
