# Generated by Django 4.1.5 on 2023-01-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(verbose_name='Birthdate'),
        ),
    ]
